name: rental_app
description: A car rental app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  dartz: 
  equatable: 
  flutter_bloc: 
  go_router:
  dio:
  get_it: 
  shared_preferences:
  flutter_secure_storage: 
  http: 
  rxdart:
  foundation:
    path: packages/foundation   
  provider:
  test: 
  firebase_core: 
  firebase_auth: 
  firebase_database:
  local_auth: 
  flex_color_scheme: 
dev_dependencies:
  bloc_test: 
  build_runner: 
  flutter_test:
    sdk: flutter
  mockito:
  mocktail: 
  flutter_lints: 

flutter:
  uses-material-design: true
