name: foundation
description: Foundation
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.18.6"


dependencies:
  flutter:
    sdk: flutter
  package_info_plus: 4.0.2
  equatable:

dev_dependencies:
  flutter_lints: ^1.0.0
flutter:
